spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useSSL=false
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
  resources:
    spring.resources.static-locations = classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
mybatis:
  mapper-locations: classpath:mapper/*.xml
